### ISSUE TITLE
[B] Can't launch online-fix games on arch-linux

### ISSUE THREAD

**Issue by AndreJorgeLopes** [BadKiko/steam-online-fix-launcher#38]
## 📌 Bug Description
Upon trying to run any game created as an online-fix game I get the following error, because of the differences between the exec command in different linux distros.

```
root INFO - [SOFL] Executing command via flatpak-spawn: sh -c 'cd /media/gamedisk/games && exec "$@"' sh --host '--env=WINEDLLOVERRIDES=d3d11=n;d3d10=n;d3d10core=n;dxgi=n;openvr_api_dxvk=n;d3d12=n;d3d12core=n;d3d9=n;d3d8=n;OnlineFix64=n,b;SteamOverlay64=n,b;winmm=n,b;dnet=n,b;steam_api64=n,b;winhttp=n,b' --env=WINEDEBUG=-all '--env=STEAM_COMPAT_DATA_PATH=/media/gamedisk/games/OFME Prefix' --env=STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/cigano/.steam/steam --env=LD_PRELOAD=/home/cigano/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so:/home/cigano/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so /home/cigano/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh /home/cigano/.local/share/Steam/compatibilitytools.d/GE-Proton10-15/proton run /media/gamedisk/games/Mars
sh: line 1: exec: --: invalid option
exec: usage: exec [-cl] [-a name] [command [argument ...]] [redirection ...]
```

## 🧩 Steps to Reproduce (ON ARCH)
1. Add game in the GUI as an online fix game
2. try and open the game

## 🖥️ Environment
- OS: Linux 6.16.8-arch3-1 | Hyprland 0.51.1 (Wayland)
- App version: 0.0.3.3a

**Comment by BadKiko** [comment]
Fixed in 0.0.3.4a

**Comment by rursache** [comment]
@BadKiko still doesn't work for me on arch (cachyos) and v0.0.3.4a:
```
❯ flatpak run org.badkiko.sofl

root INFO - Direct Steam API Runner
root INFO - [SOFL] Executing command via flatpak-spawn: sh -c 'cd /run/user/1000/doc/53aca64f && exec "$@"' sh flatpak-spawn --host '--env=WINEDLLOVERRIDES=d3d11=n;d3d10=n;d3d10core=n;dxgi=n;openvr_api_dxvk=n;d3d12=n;d3d12core=n;d3d9=n;d3d8=n;steam_api64=n,b;Custom=n,b;winmm=n,b;OnlineFix64=n,b;SteamOverlay64=n,b;GameAssembly=n,b' --env=WINEDEBUG=-all --env=STEAM_COMPAT_DATA_PATH=/home/radu/.var/app/org.badkiko.sofl/data/wine-prefixes/56413c59 --env=STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/radu/.steam/steam --env=LD_PRELOAD=/home/radu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so:/home/radu/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so /home/radu/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh '/home/radu/.local/share/Steam/steamapps/common/Proton - Experimental/proton' run /run/user/1000/doc/53aca64f/HouseFlipper2.exe
ERROR: ld.so: object '/home/radu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 193869 != 193868, skipping destruction (fork without exec?)
pid 193870 != 193868, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/radu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/radu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/radu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/radu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/radu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/radu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/radu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/radu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
fsync: up and running.
ERROR: ld.so: object '/home/radu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/radu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/radu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/radu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/radu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/radu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/radu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/radu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 193876 != 193875, skipping destruction (fork without exec?)
```
