### ISSUE TITLE
[B] Microsoft Visual C++ 2015-2022 error.

### ISSUE THREAD

**Issue by shlurd04** [BadKiko/steam-online-fix-launcher#48]
<img width="282" height="129" alt="Image" src="https://github.com/user-attachments/assets/62a7dbe3-bc93-4aba-9b4e-73255b55327f" />

not sure if bug or not, just would like some help as everything was working perfect yesterday now im getting this when i try launch a game.

**Comment by shlurd04** [comment]
I think I found the issue, for some reason my SOFL isnt generating a wine/proton prefix at ~/.local/share, not sure why. I just tried on a fresh install of Arch Linux and still having the same issue

**Comment by BadKiko** [comment]
Yeah, that’s a bug - by default, SOFL doesn’t have the C++ Redist installed right now. I’m planning an update soon that’ll include the online-fix patches and install all the main dependencies into the prefix.

**Comment by shlurd04** [comment]
is there anyway to fix this temporarily before you release this update. thank you. 

edit : I found my issue, i was launching using "/RV There Yet/ride.exe" instead of "RV There Yet/Ride/Binaries/Win64/Ride-Win64-Shipping.exe" game launches perfectly now after this fix and everything is working including steam overlay etc... so this was probably an issue on my end not a bug :)

<img width="960" height="568" alt="Image" src="https://github.com/user-attachments/assets/9fc51dad-2f88-42b8-92c0-3ac81b8d9970" />

<img width="848" height="573" alt="Image" src="https://github.com/user-attachments/assets/11996142-c646-4d5e-8ca7-2f64de6c7a94" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/4332c649-7089-4c42-b5f0-fc40f5f356ed" />

**Comment by PantherAlt** [comment]
Hello! 
i have the same problem of "shlurd04".But the game do not start, the message is: 
"Failed to open descriptor file ../../../1000/Ride.uproject"

**Comment by shlurd04** [comment]
> Hello! i have the same problem of "shlurd04".But the game do not start, the message is: "Failed to open descriptor file ../../../1000/Ride.uproject"

@PantherAlt make sure you are launching with the file i mentioned in my fix above and not ride.exe! enjoy.

**Comment by BadKiko** [comment]
Yeah, there’s this issue where the installer just grabs the first .exe it finds that’s not on the blacklist. I’ll try to expand the blacklist, but that’s still not a 100% fix.

**Comment by colelisiongaming** [comment]
> > Hello! i have the same problem of "shlurd04".But the game do not start, the message is: "Failed to open descriptor file ../../../1000/Ride.uproject"
> 
> [@PantherAlt](https://github.com/PantherAlt) make sure you are launching with the file i mentioned in my fix above and not ride.exe! enjoy.

I am using /home/colelision/onlinegames/RV There Yet/Ride/Binaries/Win64/Ride-Win64-Shipping.exe
as executable Still getting a assertion failed error
 
Full error is Wine C++ Runtime Library

Assertion failed!

Program: Z:\home\colelision\onlinegames\RV There Yet\Ride\Binaries\Win64\Ride-Win64-Shipping.exe
File: ../src-wine/dlls/winevulkan/loader_thunks.c
Line: 6428

Expression: "!status && 'vkQueuePresentKHR'"

Press OK to exit the program, or Cancel to start the Wine debugger.

**Comment by BadKiko** [comment]
I’ve released a new version 0.0.3.5a (pre-release). It hasn’t been thoroughly tested - I haven’t even been able to test the Arch image yet since I don’t have access to Arch Linux. The Debian version runs, though. There are also some new features, including auto-installing the VS C++ Redist, but I haven’t had a chance to test them! It would be great if you could give feedback on whether SOFL works or not - that’s why it’s a pre-release.

**Comment by colelisiongaming** [comment]
> I’ve released a new version 0.0.3.5a (pre-release). It hasn’t been thoroughly tested - I haven’t even been able to test the Arch image yet since I don’t have access to Arch Linux. The Debian version runs, though. There are also some new features, including auto-installing the VS C++ Redist, but I haven’t had a chance to test them! It would be great if you could give feedback on whether SOFL works or not - that’s why it’s a pre-release.

Alright I have wiped my flatpak data (warehouse) and reinstalled the new pre release I am still getting the Assertion failed! error on my laptop i7 ultra series 1 framework 13. It should be said that adding as a non steam game does also not work for me and my path is /home/USER/Downloads/RV-There-Yet/Ride/Binaries/Win64/Ride-Win64-Shipping.exe

This app and non steam game works on my Nvidia desktop however.

**Comment by dmetrei879** [comment]
помогите с проблемой "Ошибка Microsoft Visual C++ 2015-2022" не могу установить

<img width="952" height="506" alt="Image" src="https://github.com/user-attachments/assets/5f85c376-b9d2-4e9d-8897-a5db07389820" />
<img width="952" height="500" alt="Image" src="https://github.com/user-attachments/assets/285a3599-02a1-484a-a072-3dc998020398" />
<img width="950" height="504" alt="Image" src="https://github.com/user-attachments/assets/f8d9c38a-6c1f-4ae4-a6c9-309c97ab1c0e" />
<img width="961" height="506" alt="Image" src="https://github.com/user-attachments/assets/c98e8076-6a9b-47e1-9ed9-8179ec7356c0" />
